# Generated by Django 4.2.23 on 2025-08-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_movimentacaoestoque_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoestoque',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produtoestoque'),
        ),
    ]
