# Generated by Django 4.2.23 on 2025-08-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_email_alter_cliente_nascimento'),
        ('estoque', '0004_remove_produtoestoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='clientes.cliente'),
        ),
    ]
