# Generated by Django 4.2.23 on 2025-09-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_movimentacaoestoque_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoestoque',
            name='preco_unitario',
            field=models.FloatField(),
        ),
    ]
