# Generated by Django 4.2.23 on 2025-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.FloatField(),
        ),
    ]
