# Generated by Django 4.2.23 on 2025-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('multibanco', 'Multibanco'), ('mbway', 'Mbway'), ('misto', 'Misto'), ('tranferencia', 'Transferencia')], max_length=50),
        ),
    ]
