# Generated by Django 4.2.23 on 2025-08-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_email_alter_cliente_nascimento'),
        ('caixa', '0002_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='sinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
