# Generated by Django 4.2.23 on 2025-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_venda_sinal_alter_venda_cliente_alter_venda_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='fatura',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], default='nao', max_length=10),
        ),
    ]
