# Generated by Django 4.2.23 on 2025-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_venda_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='profissional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('multibanco', 'Multibanco'), ('mbway', 'Mbway'), ('misto', 'Misto'), ('Tranferencia', 'Transferencia')], max_length=50),
        ),
    ]
