# Generated by Django 4.2.23 on 2025-09-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_venda_observacoes_venda_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Multibanco', 'Multibanco'), ('Mbway', 'Mbway'), ('Misto', 'Misto'), ('Tranferencia', 'Transferencia')], max_length=50),
        ),
    ]
