# Generated by Django 4.2.23 on 2025-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('multibanco', 'Multibanco'), ('mbway', 'Mbway'), ('misto', 'Misto'), ('Tranferencia', 'Transferencia'), ('pendente', 'Pendente'), ('saida', 'Saida')], max_length=50),
        ),
    ]
