# Generated by Django 4.2.23 on 2025-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0010_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='nome_servico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='quantidade',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
