# Generated by Django 4.2.23 on 2025-11-11 15:40

from django.db import migrations
from servicos.models import Servico
from estoque.models import ProdutoEstoque
from caixa.models import VendaItem

def preencher_campos_congelados(apps, schema_editor):
    VendaItem = apps.get_model('caixa', 'VendaItem')
    ProdutoEstoque = apps.get_model('estoque', 'ProdutoEstoque')
    Servico = apps.get_model('servicos', 'Servico')

    for item in VendaItem.objects.all():
        updated = False

        # se existe produto relacionado e nome_produto vazio -> copia
        if item.produto_id and (not item.nome_produto):
            try:
                prod = ProdutoEstoque.objects.get(pk=item.produto_id)
                item.nome_produto = prod.nome
                # só escreve valor se valor_unitario estiver vazio ou zero - ajusta conforme quiser
                if not item.valor_unitario:
                    item.valor_unitario = prod.preco_unitario
                updated = True
            except ProdutoEstoque.DoesNotExist:
                pass

        # se existe serviço relacionado e nome_servico vazio -> copia
        if item.servico_id and (not item.nome_servico):
            try:
                serv = Servico.objects.get(pk=item.servico_id)
                item.nome_servico = serv.nome
                if not item.valor_unitario:
                    item.valor_unitario = serv.preco
                updated = True
            except Servico.DoesNotExist:
                pass

        if updated:
            item.save(update_fields=['nome_produto', 'nome_servico', 'valor_unitario'])

       

def desfazer_populacao(apps, schema_editor):
    VendaItem = apps.get_model('caixa', 'VendaItem')
    for item in VendaItem.objects.all():
        item.nome_produto = None
        item.nome_servico = None
        item.save(update_fields=['nome_produto', 'nome_servico'])


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0011_vendaitem_nome_produto_vendaitem_nome_servico_and_more'),
    ]

    operations = [
        migrations.RunPython(preencher_campos_congelados, desfazer_populacao),
    ]
