# Generated by Django 4.2.23 on 2025-07-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('nascimento', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('nif', models.CharField(max_length=12)),
            ],
        ),
    ]
