# Generated by Django 4.2.23 on 2025-07-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_servico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
