# Generated by Django 4.2.23 on 2025-07-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_delete_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sobrenome',
        ),
    ]
