# Generated by Django 4.2.23 on 2025-09-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_email_alter_cliente_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='clientes.cliente')),
            ],
        ),
    ]
