# Generated by Django 4.2.23 on 2025-09-07 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_fichacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichacliente',
            name='descricao',
        ),
        migrations.AddField(
            model_name='fichacliente',
            name='homecare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichacliente',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichacliente',
            name='procedimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichacliente',
            name='profissional',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fichacliente',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fichacliente',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
